package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.03 13:02:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi60 */
  @Test
  public void testRekisteroi60() {    // Kategoria: 60
    Kategoria huoneKalu = new Kategoria(); 
    assertEquals("From: Kategoria line: 62", 0, huoneKalu.getTunnusNro()); 
    huoneKalu.rekisteroi(); 
    Kategoria lastenTarvikkeet = new Kategoria(); 
    assertEquals("From: Kategoria line: 65", 0, lastenTarvikkeet.getTunnusNro()); 
    lastenTarvikkeet.rekisteroi(); 
    int n1 = huoneKalu.getTunnusNro(); 
    int n2 = lastenTarvikkeet.getTunnusNro(); 
    assertEquals("From: Kategoria line: 69", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse134 */
  @Test
  public void testParse134() {    // Kategoria: 134
    Kategoria kat = new Kategoria(); 
    kat.parse("7 | huonekalut | talon sisustamiseen"); 
    assertEquals("From: Kategoria line: 137", 7, kat.getTunnusNro()); 
    kat.toString().startsWith("007|huonekalut|talon sisustamiseen"); 
    kat.rekisteroi(); 
    int n = kat.getTunnusNro(); 
    kat.parse("" + (n + 2)); 
    kat.rekisteroi(); 
    assertEquals("From: Kategoria line: 143", n + 2 + 1, kat.getTunnusNro()); 
  } // Generated by ComTest END
}