package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.23 15:56:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi64 */
  @Test
  public void testRekisteroi64() {    // Kategoria: 64
    Kategoria huoneKalu = new Kategoria(); 
    assertEquals("From: Kategoria line: 66", 0, huoneKalu.getTunnusNro()); 
    huoneKalu.rekisteroi(); 
    Kategoria lastenTarvikkeet = new Kategoria(); 
    assertEquals("From: Kategoria line: 69", 0, lastenTarvikkeet.getTunnusNro()); 
    lastenTarvikkeet.rekisteroi(); 
    int n1 = huoneKalu.getTunnusNro(); 
    int n2 = lastenTarvikkeet.getTunnusNro(); 
    assertEquals("From: Kategoria line: 73", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse164 */
  @Test
  public void testParse164() {    // Kategoria: 164
    Kategoria kat = new Kategoria(); 
    kat.parse("7 | huonekalut | talon sisustamiseen"); 
    assertEquals("From: Kategoria line: 167", 7, kat.getTunnusNro()); 
    kat.toString().startsWith("007|huonekalut|talon sisustamiseen"); 
    kat.rekisteroi(); 
    int n = kat.getTunnusNro(); 
    kat.parse("" + (n + 2)); 
    kat.rekisteroi(); 
    assertEquals("From: Kategoria line: 173", n + 2 + 1, kat.getTunnusNro()); 
  } // Generated by ComTest END
}