package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.23 15:56:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiitosTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi48 */
  @Test
  public void testRekisteroi48() {    // Liitos: 48
    Liitos liitos = new Liitos(); 
    liitos.rekisteroi(4, 6); 
    assertEquals("From: Liitos line: 51", 1, liitos.getYhdysNro()); 
    assertEquals("From: Liitos line: 52", 4, liitos.getTuoteNro()); 
    assertEquals("From: Liitos line: 53", 6, liitos.getKatNro()); 
    Liitos liitos2 = new Liitos(); 
    liitos2.rekisteroi(2, 5); 
    assertEquals("From: Liitos line: 56", "1|4|6", liitos.toString()); 
    assertEquals("From: Liitos line: 57", "2|2|5", liitos2.toString()); 
  } // Generated by ComTest END
}