package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.23 15:56:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MyyntiPaikkaTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista37 
   * @throws SailoException when error
   */
  @Test
  public void testPoista37() throws SailoException {    // MyyntiPaikka: 37
    MyyntiPaikka kirppis = new MyyntiPaikka(); 
    Tuote mopo = new Tuote(); 
    kirppis.lisaa(mopo); 
    assertEquals("From: MyyntiPaikka line: 42", 1, kirppis.getTuotteet()); 
    Tuote mopo2 = new Tuote(); 
    Tuote mopo3 = new Tuote(); 
    kirppis.lisaa(mopo2); 
    kirppis.lisaa(mopo3); 
    assertEquals("From: MyyntiPaikka line: 47", 3, kirppis.getTuotteet()); 
    assertEquals("From: MyyntiPaikka line: 48", mopo2, kirppis.annaTuote(1)); 
  } // Generated by ComTest END
}