package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.16 16:13:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuotteetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa43 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testLisaa43() throws IndexOutOfBoundsException {    // Tuotteet: 43
    Tuotteet tuotteet = new Tuotteet(); 
    Tuote potkuKelkka = new Tuote(); 
    Tuote potkuKelkka2 = new Tuote(); 
    assertEquals("From: Tuotteet line: 48", 0, tuotteet.getLkm()); 
    tuotteet.lisaa(potkuKelkka); assertEquals("From: Tuotteet line: 49", 1, tuotteet.getLkm()); 
    tuotteet.lisaa(potkuKelkka2); assertEquals("From: Tuotteet line: 50", 2, tuotteet.getLkm()); 
    tuotteet.lisaa(potkuKelkka); assertEquals("From: Tuotteet line: 51", 3, tuotteet.getLkm()); 
    assertEquals("From: Tuotteet line: 52", potkuKelkka, tuotteet.anna(0)); 
    assertEquals("From: Tuotteet line: 53", potkuKelkka2, tuotteet.anna(1)); 
    assertEquals("From: Tuotteet line: 54", potkuKelkka, tuotteet.anna(0)); 
    assertEquals("From: Tuotteet line: 55", false, tuotteet.anna(1) == potkuKelkka); 
    assertEquals("From: Tuotteet line: 56", true, tuotteet.anna(1) == potkuKelkka2); 
    try {
    assertEquals("From: Tuotteet line: 57", potkuKelkka, tuotteet.anna(150)); 
    fail("Tuotteet: 57 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    tuotteet.lisaa(potkuKelkka); assertEquals("From: Tuotteet line: 58", 4, tuotteet.getLkm()); 
    tuotteet.lisaa(potkuKelkka); assertEquals("From: Tuotteet line: 59", 5, tuotteet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista89 */
  @Test
  public void testPoista89() {    // Tuotteet: 89
    Tuotteet tuotteet = new Tuotteet(); 
    Tuote mopo = new Tuote(), mopo2 = new Tuote(), mopo3 = new Tuote(); 
    mopo.rekisteroi(); mopo2.rekisteroi(); mopo3.rekisteroi(); 
    tuotteet.lisaa(mopo); tuotteet.lisaa(mopo2); tuotteet.lisaa(mopo3); 
    assertEquals("From: Tuotteet line: 94", 3, tuotteet.getLkm()); 
    tuotteet.poista(1); 
    assertEquals("From: Tuotteet line: 96", 2, tuotteet.getLkm()); 
  } // Generated by ComTest END
}