package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.23 15:56:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuoteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi77 */
  @Test
  public void testRekisteroi77() {    // Tuote: 77
    Tuote potkuKelkka = new Tuote(); 
    assertEquals("From: Tuote line: 79", 0, potkuKelkka.getTunnusNro()); 
    potkuKelkka.rekisteroi(); 
    Tuote kesaMekko = new Tuote(); 
    assertEquals("From: Tuote line: 82", 0, kesaMekko.getTunnusNro()); 
    kesaMekko.rekisteroi(); 
    int n1 = potkuKelkka.getTunnusNro(); 
    int n2 = kesaMekko.getTunnusNro(); 
    assertEquals("From: Tuote line: 86", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse233 */
  @Test
  public void testParse233() {    // Tuote: 233
    Tuote tuote = new Tuote(); 
    tuote.parse("3  | potkukelkka | 20€"); 
    assertEquals("From: Tuote line: 236", 3, tuote.getTunnusNro()); 
    assertEquals("From: Tuote line: 237", true, tuote.toString().startsWith("003|potkukelkka|20,0|")); 
    tuote.rekisteroi(); 
    int n = tuote.getTunnusNro(); 
    tuote.parse("" + (n+20)); 
    tuote.rekisteroi(); 
    assertEquals("From: Tuote line: 242", n+20+1, tuote.getTunnusNro()); 
  } // Generated by ComTest END
}