package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.03 13:01:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuoteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi63 */
  @Test
  public void testRekisteroi63() {    // Tuote: 63
    Tuote potkuKelkka = new Tuote(); 
    assertEquals("From: Tuote line: 65", 0, potkuKelkka.getTunnusNro()); 
    potkuKelkka.rekisteroi(); 
    Tuote kesaMekko = new Tuote(); 
    assertEquals("From: Tuote line: 68", 0, kesaMekko.getTunnusNro()); 
    kesaMekko.rekisteroi(); 
    int n1 = potkuKelkka.getTunnusNro(); 
    int n2 = kesaMekko.getTunnusNro(); 
    assertEquals("From: Tuote line: 72", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse139 */
  @Test
  public void testParse139() {    // Tuote: 139
    Tuote tuote = new Tuote(); 
    tuote.parse("3  | potkukelkka | 20€"); 
    assertEquals("From: Tuote line: 142", 3, tuote.getTunnusNro()); 
    assertEquals("From: Tuote line: 143", true, tuote.toString().startsWith("3|potkukelkka|20.0€|")); 
    tuote.rekisteroi(); 
    int n = tuote.getTunnusNro(); 
    tuote.parse("" + (n+20)); 
    tuote.rekisteroi(); 
    assertEquals("From: Tuote line: 148", n+20+1, tuote.getTunnusNro()); 
  } // Generated by ComTest END
}