package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.10 13:59:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuotteetTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa44 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testLisaa44() throws IndexOutOfBoundsException {    // Tuotteet: 44
    Tuotteet tuotteet = new Tuotteet(); 
    Tuote potkuKelkka = new Tuote(); 
    Tuote potkuKelkka2 = new Tuote(); 
    assertEquals("From: Tuotteet line: 49", 0, tuotteet.getLkm()); 
    tuotteet.lisaa(potkuKelkka); assertEquals("From: Tuotteet line: 50", 1, tuotteet.getLkm()); 
    tuotteet.lisaa(potkuKelkka2); assertEquals("From: Tuotteet line: 51", 2, tuotteet.getLkm()); 
    tuotteet.lisaa(potkuKelkka); assertEquals("From: Tuotteet line: 52", 3, tuotteet.getLkm()); 
    assertEquals("From: Tuotteet line: 53", potkuKelkka, tuotteet.anna(0)); 
    assertEquals("From: Tuotteet line: 54", potkuKelkka2, tuotteet.anna(1)); 
    assertEquals("From: Tuotteet line: 55", potkuKelkka, tuotteet.anna(0)); 
    assertEquals("From: Tuotteet line: 56", false, tuotteet.anna(1) == potkuKelkka); 
    assertEquals("From: Tuotteet line: 57", true, tuotteet.anna(1) == potkuKelkka2); 
    try {
    assertEquals("From: Tuotteet line: 58", potkuKelkka, tuotteet.anna(150)); 
    fail("Tuotteet: 58 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    tuotteet.lisaa(potkuKelkka); assertEquals("From: Tuotteet line: 59", 4, tuotteet.getLkm()); 
    tuotteet.lisaa(potkuKelkka); assertEquals("From: Tuotteet line: 60", 5, tuotteet.getLkm()); 
  } // Generated by ComTest END
}