package kirppis.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirppis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.19 15:51:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuoteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi61 */
  @Test
  public void testRekisteroi61() {    // Tuote: 61
    Tuote potkuKelkka = new Tuote(); 
    assertEquals("From: Tuote line: 63", 0, potkuKelkka.getTunnusNro()); 
    potkuKelkka.rekisteroi(); 
    Tuote kesaMekko = new Tuote(); 
    assertEquals("From: Tuote line: 66", 0, kesaMekko.getTunnusNro()); 
    kesaMekko.rekisteroi(); 
    int n1 = potkuKelkka.getTunnusNro(); 
    int n2 = kesaMekko.getTunnusNro(); 
    assertEquals("From: Tuote line: 70", n2-1, n1); 
  } // Generated by ComTest END
}